language: node_js

stages:
- build
- test
- deploy

matrix:
  include:
  - stage: build
    os: linux
    node_js: 'v13.6.0'
    script:
    - ./emscripten/sources.sh
    - ./genisoimage/sources.sh
    - ./scripts/build.sh
    - ./scripts/build-cache.sh
