language: node_js

stages:
- build
- test
- deploy

matrix:
  include:
  - stage: build
    os: linux
    node_js: 'v13.6.0'
    script:
    - ./emscripten/sources.sh
    - ./genisoimage/sources.sh
    - ./scripts/build.sh
    - ./scripts/build-cache.sh "${TRAVIS_BUILD_NUMBER}"

  - stage: test
    os: linux
    node_js: 'v8.0.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh

  - stage: test
    os: osx
    node_js: 'v8.0.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh

  - stage: test
    os: windows
    node_js: 'v8.0.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh

  - stage: test
    os: linux
    node_js: 'v13.6.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh

  - stage: test
    os: osx
    node_js: 'v13.6.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh

  - stage: test
    os: windows
    node_js: 'v13.6.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh

  - stage: deploy
    os: linux
    node_js: 'v13.6.0'
    script:
    - ./scripts/build-cached.sh "${TRAVIS_BUILD_NUMBER}"
    - ./scripts/test.sh
    deploy:
      provider: npm
      edge: true
      skip_cleanup: true
      email: $NPM_EMAIL_ADDRESS
      api_key: $NPM_API_KEY
      on:
        tags: true
