language: node_js

stages:
- test
- deploy

matrix:
  include:
  - stage: test
    os: linux
    node_js: 'v8.0.0'

  - stage: test
    os: windows
    node_js: 'v8.0.0'
    services:
    - docker

  - stage: test
    os: linux
    node_js: 'v13.6.0'

  - stage: test
    os: windows
    node_js: 'v13.6.0'
    services:
    - docker

script:
- ./emscripten/sources.sh
- ./genisoimage/sources.sh
- ./scripts/build.sh
- ./scripts/test.sh
